### ISSUE TITLE
call anim.start failed, with a error out: 'int' object isn't callable

### ISSUE THREAD

**Issue by CristXu** [lvgl/lv_binding_micropython#138]
Hi, 
    Recently, i want to set a animation for my obj with:
    **anim = lv.anim_t()
    anim.init()
    anim.set_var(ui_screen_arc4)
    anim.set_custom_exec_cb(arc_anim)
    anim.set_values(0, 360)
    anim.set_repeat_count(0xffff)
    anim.start()**
    
     But, when run to anim.start()， a error out: 'int' object isn't callable
     It seems that when i call the anim.start(), the MP find this **start** function from the anim->mp_lv_anim_t_attr: case MP_QSTR_start: dest[0] = mp_obj_new_int(data->start); break;, i want to say if this is normal?

Thanks.

**Comment by amirgon** [comment]
This is a known problem on v7, see https://github.com/lvgl/lv_examples/issues/83#issuecomment-727273239-permalink:~:text=The%20reason%20we%20call%20lv.anim_t.start(a)%20and,which%20shadows%20the%20member%20function%20lv_anim_start.

The workaround on LVGL v7 is to use `lv.anim_t.start(anim)` instead of `anim.start()`.

On LVGL v8 the problem is solved by renaming`start` to `start_value` on `lv_anim_t`

Related: https://github.com/lvgl/lvgl/issues/1763#issue-689089014
