### ISSUE TITLE
Update the webassembly part to to latest master

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_binding_micropython#289]
In the latest LVGL master the handling of GC roots was updated. 
@embeddedt, do you have some free time to update the webassembly port? 

We have tried it, but it crashed with memory access error. Probably we are missing something, but we can't see what.

**Comment by kisvegabor** [comment]
Thank you! 

Right now we are using the 
- `feat/multi-instance` branch of both `lv_micropython` and `lv_binding_mictopython`
- `master` brach of `lvgl`

The CI is passing, but we have disabled some MicroPython examples because they weren't updated yet with the latest MicroPython changes.

**Comment by kisvegabor** [comment]
cc @leidto

**Comment by embeddedt** [comment]
@kisvegabor I think I have found the issue after some debugging. The `lv_initialized` variable was moved into the new globals structure, which is only initialized when `lv_init` is called. However there are functions which call `lv_is_initialized` before `lv_init` (such as the constructor in [`display_driver_utils`](https://raw.githubusercontent.com/littlevgl/lv_binding_micropython/fa21952c6a54373ac91d4f5f9ed3752a664ee995/lib/display_driver_utils.py)), and at that time, `LV_GLOBAL_DEFAULT()` is not initialized yet. This causes a segfault if debug is enabled, and weird behavior consistent with memory corruption otherwise.

To confirm this theory I replaced `lv_initialized` with a static variable, after which the GUI appears to initialize and run without problems.

**Comment by kisvegabor** [comment]
Thank you! Could you try if modifying `lv_is_initialized()` like this solves the issue?
```c
bool lv_is_initialized(void)
{
#if LV_ENABLE_GLOBAL_CUSTOM
    if(LV_GLOBAL_DEFAULT()) return lv_initialized;
    else return false;
#else
    return lv_initialized;
#endif
}
```

**Comment by embeddedt** [comment]
Yes, this works.

**Comment by kisvegabor** [comment]
Great, I've just added the above changes.

**Comment by kisvegabor** [comment]
@embeddedt Could you confirm if the JS port is working with the latest LVGL master and if so update it?

**Comment by embeddedt** [comment]
Typically @amirgon and I have had an unwritten convention where the main `master` branch of lv_micropython is updated first and then I merge it to the JS branch. Just wanted to clarify that the multi-instance changes are special and I should update JS out-of-order?

**Comment by embeddedt** [comment]
Updated and deployed. :+1:

**Comment by kisvegabor** [comment]
Thank you :pray:
